name = "paymaster-cf-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "2ff7a66618cc5f0d9a5ab90044188748"

[vars]
# PAYMASTER_PRIVATE_KEY is now in .dev.vars for security
EOA_DELEGATION_ADDRESS = "0x0977081db8717cb860716edcd117ef1fbf108857" # Updated EOADelegation contract address (Arbitrum Sepolia)
EIP7702_PAYMASTER_ADDRESS = "0x53cd866553b78a32060b70e764d31b0fe3afe52c" # Paymaster address (Arbitrum Sepolia)
SMART_WALLET_FACTORY_ADDRESS = "0x884ff7a379192ef709e0d865d52adfa967e1ab94" # Updated SmartWalletFactory contract address (Arbitrum Sepolia)
PYUSD_ADDRESS = "0x637A1259C6afd7E3AdF63993cA7E58BB438aB1B1" # Real PYUSD token address (Arbitrum Sepolia)
RPC_URL = "https://sepolia-rollup.arbitrum.io/rpc" # Arbitrum Sepolia RPC

[env.production]
name = "paymaster-cf-worker-prod"

[env.development]
name = "paymaster-cf-worker-dev"

# KV namespaces for storing data (commented out - not needed for this worker)
# [[kv_namespaces]]
# binding = "PAYMASTER_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
