name = "paymaster-cf-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
PAYMASTER_PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Hardhat account #0 private key for testing
EOA_DELEGATION_ADDRESS = "YOUR_EOA_DELEGATION_ADDRESS" # EOADelegation contract address
EIP7702_PAYMASTER_ADDRESS = "YOUR_EIP7702_PAYMASTER_ADDRESS" # EIP7702Paymaster contract address
SMART_WALLET_FACTORY_ADDRESS = "YOUR_SMART_WALLET_FACTORY_ADDRESS" # SmartWalletFactory contract address
RPC_URL = "http://127.0.0.1:8545" # Local Hardhat node

[env.production]
name = "paymaster-cf-worker-prod"

[env.development]
name = "paymaster-cf-worker-dev"

# KV namespaces for storing data
[[kv_namespaces]]
binding = "PAYMASTER_KV"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"
