name = "paymaster-cf-worker"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "2ff7a66618cc5f0d9a5ab90044188748"

[vars]
# PAYMASTER_PRIVATE_KEY is now in .dev.vars for security
EOA_DELEGATION_ADDRESS = "0x02d6ab26b2b5448a0b123725926c5b9c2bc6faa6" # EOADelegation contract address (Arbitrum Sepolia)
EIP7702_PAYMASTER_ADDRESS = "0x937884bf26c66d53aeb6a1a3bf02cdbb4bc0d8ee" # EIP7702Paymaster contract address (Arbitrum Sepolia)
SMART_WALLET_FACTORY_ADDRESS = "0xe16ae63bf10ad8e0522f7b79dc21fdc72f9e86d9" # SmartWalletFactory contract address (Arbitrum Sepolia)
PYUSD_ADDRESS = "0x637A1259C6afd7E3AdF63993cA7E58BB438aB1B1" # Real PYUSD token address (Arbitrum Sepolia)
RPC_URL = "https://sepolia-rollup.arbitrum.io/rpc" # Arbitrum Sepolia RPC

[env.production]
name = "paymaster-cf-worker-prod"

[env.development]
name = "paymaster-cf-worker-dev"

# KV namespaces for storing data (commented out - not needed for this worker)
# [[kv_namespaces]]
# binding = "PAYMASTER_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"
